### ISSUE TITLE
This plugin doesn't hide a chapter, it stops it from building

### ISSUE THREAD

**Issue by jakubgs** [ankitrgadiya/mdbook-hide#1]
I though this plugin could allow me to have chapters that are hidden from the navbar but navigable via URL, but that's not the case.

As far as I can tell the `hidden` comment simply stops it from being built, is that correct? Or am I missing something?

**Comment by ankitrgadiya** [comment]
@jakubgs Yes, that is correct, it excludes the pages from the build entirely.

**Comment by jakubgs** [comment]
Thanks for clarifying. Not really what I'm looking for.

I described my workaround here: https://github.com/rust-lang/mdBook/issues/1821#issuecomment-1777386535
